Scenario: Level1
StartResources: 200
VictoryCondition: "Collect 1500 Resources"
Buildings:
  - Type: Drill
    Row: 2
    Col: 3
    Level: 1
  - Type: Excavator
    Row: 4
    Col: 5
    Level: 2
UnplacableCells:
  - Row: 1
    Col: 1
  - Row: 3
    Col: 3
BuildingTypes:
  - Type: Drill
    Cost: 100
    Rate: 10
    Scale: 1.0
  - Type: Excavator
    Cost: 200
    Rate: 20
    Scale: 1.2
  - Type: Refinery
    Cost: 500
    Rate: 50
    Scale: 1.5
