gridConfig:
  width: 8
  height: 8
  size: 50

buildings:
  - type: Drill
    cost: 10
    rate: 1
    scale: 1.6
    growthRule: default
  - type: Excavator
    cost: 30
    rate: 1.5
    scale: 1.6
    growthRule: waterSun
  - type: DemolitionPlant
    cost: 50
    rate: 2
    scale: 1.6
    growthRule: default

RESOURCE_GOAL: 1000

trackables:
  buildingsPlaced: 0
  resourcesCollected: 0
  turnsPlayed: 0

victoryCondition:
  type: specificBuilding
  goal: 1
  buildingType: Drill