gridConfig:
  width: 8
  height: 8
  size: 50

buildings:
  - type: Drill
    cost: 10
    rate: 1
    scale: 1.6
    growthRule: default
  - type: Excavator
    cost: 30
    rate: 1.5
    scale: 1.6
    growthRule: waterSun
  - type: DemolitionPlant
    cost: 50
    rate: 2
    scale: 1.6
    growthRule: default

trackables:
  buildingsPlaced: 0
  resourcesCollected: 0
  turnsPlayed: 0

victoryCondition:
  type: resources
  goal: 1000

startingResources: 100

weatherCondition:
  type: drought
  startTurn: 3
  endTurn: 5