gridConfig:
  width: 8
  height: 8
  cellSize: 50

buildings:
  - type: Drill
    cost: 10
    rate: 1
    scale: 1.6
  - type: Excavator
    cost: 30
    rate: 1.5
    scale: 1.6
  - type: DemolitionPlant
    cost: 50
    rate: 2
    scale: 1.6

RESOURCE_GOAL: 1000

trackables:
  buildingsPlaced: 0
  resourcesCollected: 0
  turnsPlayed: 0