# Workflow provided by Brace
name: Phaser 3 Build and Deploy

# This workflow triggers on push to the main branch or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Phaser Game
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust to your preferred Node.js version

      # Step 3: Install dependencies (ensure you have a package.json in your repo)
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Phaser project
      # Assuming your Phaser project has a build script defined in package.json
      - name: Build the game
        run: npm run build

      # Step 5: Archive build artifacts (optional for debugging purposes)
      - name: Upload build artifacts for debugging
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    # Deploy the "dist" folder (where Phaser build files live) to GitHub Pages
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy the dist folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
